backend/config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'
  get 'errors/unacceptable'
  get 'errors/internal_error'

  # Custom error pages
  get "/404" => "errors#not_found"
  get "/422" => "errors#unacceptable"
  get "/500" => "errors#internal_error"

  # REST API session routes
  get "/auth/:provider/callback" => "api/sessions#create"
  get "/signout" => "api/sessions#destroy", :as => :signout
  get "/authenticate" => "api/sessions#authenticate"
  get "/is_logged_in" => "api/sessions#is_logged_in"
  get "/unauthorized" => "api/sessions#unauthorized", :as => :unauthorized
  get "/unauthorized_key" => "api/sessions#unauthorized_key", :as => :unauthorized_key

  # Get locations near gps coordinates
  get '/api/v1/locations/near' => 'api/v1/locations#near', :as => :locations_near

  # Search for locations
  get '/api/v1/locations/search' => 'api/v1/locations#search', :as => :locations_search

  # Search for reports
  get '/api/v1/reports/search' => 'api/v1/reports#search', :as => :reports_search

  # Get reports with specific tag
  get '/api/v1/tags/:id/reports' => 'api/v1/tags#reports', :as => :tag_reports

  # Add and remove tags for report
  post '/api/v1/reports/:report_id/tag/:tag_id' => 'api/v1/reports#add_tag', :as => :report_add_tag
  delete '/api/v1/reports/:report_id/tag/:tag_id' => 'api/v1/reports#remove_tag', :as => :report_remove_tag

  namespace :api, defaults: {format: 'json'} do

    namespace :v1 do

      resources :locations
      resources :tags
      resources :reports

    end

  end


  # API-key App specific routes
  root 'users#login'
  resources :users
  resources :keys, :except => [:index]

  get 'userkeys' => 'keys#show', as: :userkeys
  get 'login' => 'users#login', as: :login
  post 'dologin' => 'users#dologin', as: :dologin
  get 'dologout' => 'users#dologout', as: :dologout

  # You can have the root of your site routed with "root"
  # root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

backend/app/models/key.rb
class Key < ActiveRecord::Base

  VALID_APP_NAME_REGEX = /\A[\w+\-.&_\såäöÅÄÖéèëÉÈËáàÁÀúùüÚÙÜóòÒÓ]+\z/i
  VALID_APP_KEY_REGEX = /\A[\w+]+\z/i

  validates :app_name,
            presence: true,
            length: {
                maximum: 100,
                minimum: 2
            },
            format: { with: VALID_APP_NAME_REGEX }

  validates :key_value,
            presence: true,
            length: {
                maximum: 100,
                minimum: 2
            },
            format: { with: VALID_APP_KEY_REGEX },
            uniqueness: true

  belongs_to :user

end

backend/app/controllers/keys_controller.rb
class KeysController < ApplicationController

  def show

    check_login

  end

  def new

    check_login

    @key = Key.new

  end

  def create

    check_login

    require 'securerandom'

    @key = Key.new(key_params)

    # Generate new random key
    @key.key_value = SecureRandom.hex(32)

    @key.user_id = current_user.id

    if @key.save

      flash[:succcess] = "Application key successfully generated."
      redirect_to userkeys_path

    else

      render :action => "new"

    end

  end

  def destroy

    check_login

    @key = Key.find(destroy_params[:id])

    # Check that user owns the key or is a admin
    if @key.user_id == current_user.id or current_user.is_admin?

      # Try to delete key
      if @key.destroy
        flash[:succcess] = "Application key successfully deleted."
      else
        flash[:danger] = "Could not delete application key."
      end

    else
      flash[:danger] = "You are not the owner of that key."
    end

  end

  private

  def key_params
    params.require(:key).permit(:app_name)
  end

  def destroy_params
    params.permit(:id)
  end

end

backend/app/helpers/keys_helper.rb
module KeysHelper
end

backend/app/views/keys/destroy.html.erb
<%= render "layouts/logged_in_header" %>

<div class="row">
  <h1>Delete API-key</h1>
</div>

<div class="row">
  <%= render "layouts/flashmessage" %>
</div>


<div class="row">
  <%= link_to_unless(current_user.is_admin?, "Back to list", userkeys_path, class: 'btn btn-lg btn-primary'){} %>

  <%= link_to_if(current_user.is_admin?, "Back to users", users_path, class: 'btn btn-lg btn-primary'){} %>
</div>

backend/app/views/keys/new.html.erb
<%= render "layouts/logged_in_header" %>

<% if @key.errors.any? %>

    <div class="row">
      <div class="alert alert-warning col-md-6">
        <h3>Errors occured</h3>

        <ul>
          <% @key.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
          <% end %>
        </ul>

      </div>
    </div>


<% end %>

<div class="row">
  <h1>New API key</h1>
</div>



<div class="row">

  <%= render "layouts/flashmessage" %>

  <%= form_for @key do |f| %>

      <p><%= f.label :app_name %></p>
      <p><%= f.text_field :app_name, :size => 100, class: 'form-control' %></p>

      <p><%= f.submit "Register app", class: 'btn btn-lg btn-primary' %></p>

  <% end %>

  <%= link_to "Back to list", userkeys_path, class: 'btn btn-default' %>
</div>

backend/app/views/keys/show.html.erb
<%= render "layouts/logged_in_header" %>

<div class="row">
  <%= render "layouts/flashmessage" %>
</div>

<div class="row">
  <h1>My API-keys</h1>
</div>

<div class="row">

  <p>Number of application keys: <%= current_user.key.count %></p>

  <table class="table table-striped">
    <thead>
    <tr>
      <th>App name</th>
      <th>Key value</th>
      <th></th>
    </tr>
    </thead>
    <tbody>
    <% current_user.key.each do |key| %>
        <tr>
          <td><%= key.app_name %></td>
          <td> <%= key.key_value %></td>
          <td><%= link_to "Delete", key, method: :delete, class: "btn btn-xs btn-default", data: { confirm: "Are you sure?" } %></td>
        </tr>
    <% end %>
    </tbody>
  </table>

  <%= link_to "Create new App key", new_key_path, class: 'btn btn-lg btn-primary'   %>

</div>