backend/config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'
  get 'errors/unacceptable'
  get 'errors/internal_error'

  # Custom error pages
  get "/404" => "errors#not_found"
  get "/422" => "errors#unacceptable"
  get "/500" => "errors#internal_error"

  # REST API session routes
  get "/auth/:provider/callback" => "api/sessions#create"
  get "/signout" => "api/sessions#destroy", :as => :signout
  get "/authenticate" => "api/sessions#authenticate"
  get "/is_logged_in" => "api/sessions#is_logged_in"
  get "/unauthorized" => "api/sessions#unauthorized", :as => :unauthorized
  get "/unauthorized_key" => "api/sessions#unauthorized_key", :as => :unauthorized_key

  # Get locations near gps coordinates
  get '/api/v1/locations/near' => 'api/v1/locations#near', :as => :locations_near

  # Search for locations
  get '/api/v1/locations/search' => 'api/v1/locations#search', :as => :locations_search

  # Search for reports
  get '/api/v1/reports/search' => 'api/v1/reports#search', :as => :reports_search

  # Get reports with specific tag
  get '/api/v1/tags/:id/reports' => 'api/v1/tags#reports', :as => :tag_reports

  # Add and remove tags for report
  post '/api/v1/reports/:report_id/tag/:tag_id' => 'api/v1/reports#add_tag', :as => :report_add_tag
  delete '/api/v1/reports/:report_id/tag/:tag_id' => 'api/v1/reports#remove_tag', :as => :report_remove_tag

  namespace :api, defaults: {format: 'json'} do

    namespace :v1 do

      resources :locations
      resources :tags
      resources :reports

    end

  end


  # API-key App specific routes
  root 'users#login'
  resources :users
  resources :keys, :except => [:index]

  get 'userkeys' => 'keys#show', as: :userkeys
  get 'login' => 'users#login', as: :login
  post 'dologin' => 'users#dologin', as: :dologin
  get 'dologout' => 'users#dologout', as: :dologout

  # You can have the root of your site routed with "root"
  # root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

backend/app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password

  VALID_NAME_REGEX = /\A[\w+\såäöÅÄÖéèëÉÈËáàÁÀúùüÚÙÜóòÒÓ]+\z/i
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name,
            presence: true,
            length: {
                maximum: 50,
                minimum: 2
            },
            format: { with: VALID_NAME_REGEX  }

  validates :email,
            presence: true,
            length: { maximum: 50, minimum: 3 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: true

  has_many :key

  has_and_belongs_to_many :roles


  ### Methods

  # Check if user has role
  def has_role?(*role_names)
    self.roles.where(:name => role_names).present?
  end

  # Return true if user is admin
  def is_admin?
    self.has_role?("Admin")
  end

end

backend/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index

    check_admin_login

    @users = User.all

  end

  def new

    @user = User.new

  end

  def create

    @user = User.new(user_params)

    if @user.save

      session[:user_id] = @user.id

      redirect_to userkeys_path

    else

      render :action => "new"

    end

  end

  ## Login methods

  def dologin

    user = User.find_by_email(params[:email])

    if user

      if user.authenticate(params[:password])

        session[:user_id] = user.id

        # If user is and admin, redirect to users
        if user.is_admin?

          redirect_to users_url

        # If user is an normal user, redirect to keys.
        else

          redirect_to userkeys_url

        end

      else

        flash[:danger] = "Wrong password, please try again."
        redirect_to login_path

      end

    else

      flash[:danger] = "Could not find a user with the email address: #{params[:email]}"
      redirect_to login_path

    end

  end

  def login



  end

  def dologout

    session[:user_id] = nil

    flash[:success] = "Successfully logged out."

    redirect_to root_path

  end


  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :name)
  end

end

backend/app/helpers/users_helper.rb
module UsersHelper
end

backend/app/views/users/index.html.erb
<%= render "layouts/logged_in_header" %>

<div class="row">
  <%= render "layouts/flashmessage" %>
</div>

<div class="row">
  <h1>All users</h1>
</div>

<div class="row">

  <p>Number of users: <%= @users.count %></p>

  <% @users.each do |user| %>

      <div class="panel panel-default">

        <div class="panel-heading">
          <h3 class="panel-title"><span class="glyphicon glyphicon-user"></span> <%= user.name %> (<%= user.email %>)</h3>
        </div>

        <div class="panel-body">

          <% if user.key.any? %>
              <table class="table table-striped">

                <thead>
                <tr>
                  <th>App name</th>
                  <th>Key value</th>
                  <th></th>
                </tr>
                </thead>
                <tbody>

                <% user.key.each do |key| %>
                    <tr>
                      <td><%= key.app_name %></td>
                      <td><%= key.key_value %></td>
                      <td><%= link_to "Delete", key, method: :delete, class: "btn btn-xs btn-default", data: { confirm: "Are you sure?" } %></td>
                    </tr>

                <% end %>

                </tbody>

              </table>

          <% else %>

              <p class="text-muted">No api-keys found</p>

          <% end %>

        </div>

      </div>



  <% end %>


</div>

backend/app/views/users/login.html.erb
<%= render "layouts/flashmessage" %>

<%= form_tag(dologin_path, method: "post", class: 'col-md-4 col-md-offset-4 jumbotron row') do %>

    <div class="row">

      <h2>Log in</h2>
      <%= label_tag(:email, "E-mail") %>
      <%= email_field_tag(:email, nil, class: 'form-control') %>

      <%= label_tag(:password, "Password") %>
      <%= password_field_tag(:password, nil, class: 'form-control') %>

      <br>

      <%= submit_tag("Login", class: 'btn btn-lg btn-primary btn-block') %>

    </div>

    <hr>

    <div class="row">
      <%= link_to "Register", new_user_path, class: 'btn btn-default' %>
    </div>

<% end %>

backend/app/views/users/new.html.erb
<%= render "layouts/flashmessage" %>

<% if @user.errors.any? %>

  <div class="row alert alert-warning col-md-6 col-md-offset-3">
    <h3>Errors occured</h3>

    <ul>
      <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>

  </div>

<% end %>

<%= form_for @user, :html => {:class => 'col-md-4 col-md-offset-4 jumbotron row'} do |f| %>
  <div class="row">
    <h2>Registration</h2>

    <%= f.label :name %>
    <%= f.text_field :name, :size => 50, class: 'form-control' %>

    <%= f.label :email %>
    <%= f.email_field :email, :size => 50, class: 'form-control' %>

    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>

    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>

    <br>

    <%= f.submit "Register", class: 'btn btn-lg btn-primary btn-block' %>



  </div>
  <hr>
  <div class="row">
    <%= link_to "To login", login_path, class: 'btn btn-default' %>
  </div>



<% end %>